services:
  api:
    build: .
    container_name: well-monitor-api
    command: uvicorn src.web:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis
  monitor:
    build: .
    container_name: well-monitor-monitor
    group_add:
      - dialout
    command: /start-monitor.sh
    environment:
      - PYTHONUNBUFFERED
      - LOG_LEVEL
      - SERIAL_PORT
      - BAUD_RATE
      - COMPOSE_PROFILES
    volumes:
      - .:/code
    depends_on:
      - redis
  simulator:
    build: .
    container_name: well-monitor-simulator
    command: /start-simulator.sh
    profiles:
      - simulate
    environment:
      - PYTHONUNBUFFERED
      - LOG_LEVEL
      - SERIAL_PORT
      - BAUD_RATE
      - LOG_FREQUENCY
      - COMPOSE_PROFILES
    volumes:
      - .:/code
    depends_on:
      - monitor
  redis:
    image: redis:alpine
