services:
  api:
    build: .
    container_name: well-monitor
    command: uvicorn src.api:app --host 0.0.0.0 --port 80 --reload; /start.sh
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis
  #monitor:
  #  build: .
  #  command: ./start.sh
  #  volumes:
  #    - .:/code
  #  #devices:
  #  #  - /dev/tty.usbserial-14520
  #  depends_on:
  #    - redis      
  redis:
    image: redis:alpine
